app.domain=https://ceres-dev.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoime.support@gmail.com
spring.mail.password=ujus mqbw boay zgrl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.root=DEBUG
logging.level.javax.management=INFO
logging.level.com.sun.jmx=INFO
logging.level.sun.rmi=INFO
logging.level.javax.management.remote.rmi=INFO
logging.level.com.sun.jmx.remote=INFO
#logging.level.com.ceres.hoime=DEBUG
